name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: lab2 autograding
      id: lab2-autograding
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: lab2 autograding
        setup-command: sudo apt-get update >/dev/null 2>&1 && sudo apt-get install
          -y qemu-system-i386 >/dev/null 2>&1 && pip3 install pwntools >/dev/null
          2>&1 && wget https://raw.githubusercontent.com/UCRCS153/UCR-CS153.github.io/main/lab2.py
          >/dev/null 2>&1
        command: python3 lab2.py
        timeout: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        LAB2-AUTOGRADING_RESULTS: "${{steps.lab2-autograding.outputs.result}}"
      with:
        runners: lab2-autograding
